name: Java CDK Synth, Zip, and Upload to S3

on:
  push:
    branches:
      - main  # Update if using a different branch

jobs:
  synth-zip-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up AWS CDK
        run: npm install -g aws-cdk

      - name: Build Java CDK project
        run: mvn clean install

      - name: Run CDK synth
        run: cdk synth

      - name: Zip the CDK project
        run: |
          zip -r cdk-project.zip . -x ".git/*" ".github/*"
          ls -lh cdk-project.zip

      - name: Upload to S3
        run: aws s3 cp cdk-project.zip s3://test-1-git/
